AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
