AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Metrics/BlockLength:
  AllowedMethods: ['feature', 'describe', 'context', 'FactoryBot.define']
Style/FormatStringToken:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Metrics/MethodLength:
  AllowedMethods: ['up', 'arel']
  Max: 20
Metrics/AbcSize:
  AllowedMethods: ['arel']
Naming/VariableNumber:
  EnforcedStyle: snake_case
